package io.spooler.demo

import io.spooler.core.DocumentType
import io.spooler.core.UnifiedKmpDocument

fun invoiceHtml(): String =
  UnifiedKmpDocument(DocumentType.A4_DOCUMENT, title = "Invoice INV-2026-0042")
    .addLogo(sampleLogoBytes(), sampleLogoType)
    .addHeader("Norims Hardware Ltd")
    .addText("P.O. Box 1234-20100, Nakuru • VAT PIN: P051234567X")
    .addDivider()
    .addTableRow("Invoice", "INV-2026-0042")
    .addTableRow("Date", "2026-07-05")
    .addTableRow("Bill To", "Rift Valley Contractors Ltd")
    .addDivider()
    .addTableRow("Description", "Qty", "Unit", "Total")
    .addTableRow("PPR Pipe 1in", "40", "300.00", "12,000.00")
    .addTableRow("Cement 50kg", "25", "780.00", "19,500.00")
    .addTableRow("Steel Bar D12", "60", "1,150.00", "69,000.00")
    .addDivider()
    .addTableRow("Subtotal", "", "", "100,500.00")
    .addTableRow("VAT (16%)", "", "", "16,080.00")
    .addTableRow("TOTAL DUE", "", "", "116,580.00")
    .addDivider()
    .addText("Payment due within 30 days. Bank: Equity 012345678, Norims Hardware Ltd.")
    .buildHtml()

fun purchaseOrderHtml(): String =
  UnifiedKmpDocument(DocumentType.A4_DOCUMENT, title = "Purchase Order PO-2026-0117")
    .addLogo(sampleLogoBytes(), sampleLogoType)
    .addHeader("Norims Hardware Ltd")
    .addText("P.O. Box 1234-20100, Nakuru • VAT PIN: P051234567X")
    .addDivider()
    .addTableRow("PO Number", "PO-2026-0117")
    .addTableRow("Supplier", "Devki Steel Mills Ltd")
    .addTableRow("Delivery Date", "2026-07-12")
    .addDivider()
    .addTableRow("Description", "Qty", "Unit", "Total")
    .addTableRow("Steel Bar D12", "200", "1,100.00", "220,000.00")
    .addTableRow("Roofing Sheets 3m", "80", "1,450.00", "116,000.00")
    .addTableRow("Wire Nails 4in", "50", "180.00", "9,000.00")
    .addDivider()
    .addTableRow("Subtotal", "", "", "345,000.00")
    .addTableRow("VAT (16%)", "", "", "55,200.00")
    .addTableRow("TOTAL", "", "", "400,200.00")
    .addDivider()
    .addText("Authorized by: Peter Mwangi, Procurement Manager")
    .addNewPage()
    .addHeader("Terms & Conditions")
    .addText("1. Goods must match the specifications and quantities stated above.")
    .addText("2. Delivery must be made to the Nakuru branch on or before the delivery date.")
    .addText("3. Payment terms: 30 days net from date of delivery and invoice receipt.")
    .addText("4. Rejected or damaged goods will be returned at the supplier's cost.")
    .buildHtml()

fun stockReportHtml(): String =
  UnifiedKmpDocument(DocumentType.A4_DOCUMENT, title = "Stock Report - Nakuru Branch")
    .addLogo(sampleLogoBytes(), sampleLogoType)
    .addHeader("Norims Hardware Ltd - Stock Report")
    .addText("Branch: Nakuru • Report Date: 2026-07-05")
    .addDivider()
    .addTableRow("SKU", "Item", "In Stock", "Reorder Level", "Status")
    .addTableRow("PPR-1IN", "PPR Pipe 1in", "180", "50", "OK")
    .addTableRow("CEM-50KG", "Cement 50kg", "22", "40", "LOW")
    .addTableRow("STL-D12", "Steel Bar D12", "310", "100", "OK")
    .addTableRow("PTFE-12M", "PTFE Tape", "8", "30", "LOW")
    .addTableRow("RFS-3M", "Roofing Sheets 3m", "64", "20", "OK")
    .addTableRow("NAIL-4IN", "Wire Nails 4in", "5", "25", "LOW")
    .addDivider()
    .addText("Total SKUs: 6 • Low Stock Items: 3")
    .buildHtml()

fun saleReceiptHtml(): String =
  UnifiedKmpDocument(DocumentType.RECEIPT_80MM, title = "Norims Receipt")
    .addLogo(sampleLogoBytes(), sampleLogoType)
    .addHeader("NORIMS HARDWARE")
    .addText("Nakuru Branch • Till 04")
    .addText("2026-07-05 14:32 • Cashier: Wanjiru")
    .addDivider()
    .addTableRow("Item", "Qty", "Amount")
    .addTableRow("PPR Pipe 1in", "4", "1,200.00")
    .addTableRow("Elbow Joint", "8", "640.00")
    .addTableRow("PTFE Tape", "3", "150.00")
    .addDivider()
    .addTableRow("Subtotal", "", "1,990.00")
    .addTableRow("VAT (16%)", "", "318.40")
    .addTableRow("TOTAL", "", "2,308.40")
    .addDivider()
    .addText("M-PESA • Ref QTR4X8P2L")
    .addText("Thank you for shopping with us!")
    .buildHtml()

fun compactReceiptHtml(): String =
  UnifiedKmpDocument(DocumentType.RECEIPT_58MM, title = "Norims Receipt")
    .addHeader("NORIMS HARDWARE")
    .addText("Naivasha Rd Kiosk")
    .addDivider()
    .addTableRow("Wire Nails 4in", "45.00")
    .addTableRow("PTFE Tape", "50.00")
    .addTableRow("Cable Ties", "30.00")
    .addDivider()
    .addTableRow("TOTAL", "125.00")
    .addText("M-PESA Ref QTR4X8P2L")
    .addText("Asante sana!")
    .buildHtml()
